version: "3.8"

services:
  votv-fans-ru:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=votv-fans.ru
      - LETSENCRYPT_HOST=votv-fans.ru
      - LETSENCRYPT_EMAIL=arseny.saw4enko@gmail.com
    expose:
      - "10000"
